### ISSUE TITLE
To-Do's

### ISSUE THREAD

**Issue by KikeM** [KikeM/Mitigating-Overfitting-Experiment#1]
- [ ]  Clean the code.

- [ ] Try with a simpler model.

- [ ] Predict returns instead of prices.
